#!/bin/sh
##################
#
# File:		create_SAMSHelp
# Purpose:	This script creates the help document using the helper scripts
# Author:	L.P.O'Mard
# Created:	29 Jan 2003
# Updated:	
# Copyright:(c) 2003, CNBH, University of Essex
#
##################

#create_help SAMS Help -h3
#mv SAMSHelp.zip ../HelpFiles
#ps2pdf SAMSHelp.prn ../HelpFiles/SAMSHelp.pdf

xmlto pdf SAMSHelp.xml

#docbook2pdf SAMSHelp.xml

cp SAMSHelp.pdf ../HelpFiles
