#!/bin/sh
##################
#
# File:		cvsconfigure
# Purpose:	This script runs all of the commands necessary for configuring DSAM
#			from the CVS repository.
# Author:	L.P.O'Mard
# Created:	21 Jun 2001
# Updated:	
# Copyright:(c) 2001, University of Essex
#
##################

if [ -f configure.in ]; then
	mv configure.in configure.in.mkaconf.save
fi

declare -x WANT_AUTOMAKE=1.8

aclocal
autoconf
automake --add-missing
ln -sf /usr/share/libtool/ltmain.sh CfgTools
