/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RunDSAMSimJ */

#ifndef _Included_RunDSAMSimJ
#define _Included_RunDSAMSimJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RunDSAMSimJ
 * Method:    RunSimScriptCPP
 * Signature: (Ljava/lang/String;Ljava/lang/String;[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_RunDSAMSimJ_RunSimScriptCPP
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
