#!/bin/sh
##################
#
# File:		dos-dist
# Purpose:	This script runs all of the commands necessary for configuring RunDSAMSim
#			for dos compilation
# Author:	L.P.O'Mard
# Created:	26 Sep 2001
# Updated:	
# Copyright:(c) 2001, L. P. O'Mard
#
##################

CFGTOOLS=CfgTools
TEMP_FILE=file.tmp
SRCDIR=src
JAVALIB=$SRCDIR/java

usage()
{
	cat <<EOF
Usage: dos-dist command
commands:
	make      - Create a zip archive distribution.
EOF
	exit $1
}

############################### CVSConfigure ###################################

CVSConfigure()
{
	sh autogen.sh
	./configure --enable-java-support
	(cd $JAVALIB; make; rm *.stamp *.class)
}

############################### Main Script ####################################

if [ $# -eq 0 ]; then
	usage 1 1>&2
fi

case  $1 in
autogen)
	CVSConfigure
	rm -f config.status config.cache
	;;
make)
	echo Creating unix distribution directory ...
	CVSConfigure > $TEMP_FILE
	make dist > $TEMP_FILE
	grep "^PACKAGE " Makefile | sed "s/ //g" > $TEMP_FILE
	grep "^VERSION " Makefile | sed "s/ //g" >> $TEMP_FILE
	source ./$TEMP_FILE
	archiveName=${PACKAGE}-${VERSION}
	echo archiveName = $archiveName
	rm -rf $archiveName
	tar zxf $archiveName.tar.gz
	rm $archiveName.tar.gz

	echo Copying extra files to archive  ...
	mv $JAVALIB/*.jar $archiveName/$JAVALIB
	
	echo Creating zip archive ...
	newArchiveName=`echo $archiveName | tr -d ".-"`
	rm -rf $newArchiveName
	mv $archiveName $newArchiveName
	zip -r $newArchiveName.zip $newArchiveName > $TEMP_FILE
	rm -rf $newArchiveName
	rm $TEMP_FILE
	make distclean

	echo Finished creating $newArchiveName.zip.
	;;
*)
	usage 1 1>&2
esac
