#!/bin/sh
##################
#
# File:		create_SSAMSTutorials
# Purpose:	This script creates the help document using the helper scripts
# Author:	L.P.O'Mard
# Created:	29 Jan 2003
# Updated:	
# Copyright:(c) 2003, CNBH, University of Essex
#
##################

create_help SSAMS Tutorials -h1
mv SSAMSTutorials.zip ../HelpFiles
ps2pdf SSAMSTutorials.prn ../HelpFiles/SSAMSTutorials.pdf
