#!/bin/sh
##################
#
# File:		create_SAMSTutorials
# Purpose:	This script creates the help document using the helper scripts
# Author:	L.P.O'Mard
# Created:	29 Jan 2003
# Updated:	
# Copyright:(c) 2003, CNBH, University of Essex
#
##################

create_help SAMS Tutorials -h1
mv SAMSTutorials.zip ../HelpFiles
ps2pdf SAMSTutorials.prn ../HelpFiles/SAMSTutorials.pdf
