#!/bin/sh
##################
#
# File:		create_AMSHelp
# Purpose:	This script creates the help document using the helper scripts
# Author:	L.P.O'Mard
# Created:	29 Jan 2003
# Updated:	
# Copyright:(c) 2003, CNBH, University of Essex
#
##################

%create_help AMS Help -h3
%mv AMSHelp.zip ../HelpFiles
%ps2pdf AMSHelp.prn ../HelpFiles/AMSHelp.pdf

%xmlto pdf AMSHelp.xml

docbook2pdf AMSHelp.xml
cp AMSHelp.pdf ../HelpFiles
