#!/bin/sh
##################
#
# File:		dos-dist
# Purpose:	This script runs all of the commands necessary for configuring DSAM
#			from the CVS repository for dos compilation
# Author:	L.P.O'Mard
# Created:	13 Jul 2001
# Updated:	
# Copyright:(c) 2001, University of Essex
#
##################

INCDIR=Include
SRCDIR=src
MAINLIB=$SRCDIR/MainLib
GRLIB=$SRCDIR/GrLib
CFGTOOLS=CfgTools
TEMP_FILE=file.tmp

usage()
{
	cat <<EOF
Usage: dos-dist command
commands:
    cvsconfig - configure the cvs source for compilation on windows platform.
    clean     - remove all windows compilation created directories and files.
	make      - Create a zip archive distribution.
EOF
	exit $1
}

if [ $# -eq 0 ]; then
	usage 1 1>&2
fi

case  $1 in
cvsconfig)
	$CFGTOOLS/cvsconfigure
	./configure
	(cd $MAINLIB; make UtSSParser.c)
	cp $MAINLIB/UtSSParser.h $INCDIR
	;;
clean)
	rm -rf lib bin $INCDIR/UtSSParser.h `find . -name '*.obj'`
	rm -f `find . -name '*.exe'`
	rm -f `find . -name '*.pch'`
	rm -f `find . -name '*.idb'`
	rm -f `find . -name '*.pdb'`
	rm -f `find . -name '*.plg'`
	rm -f `find . -name '*.ncb'`
	rm -f `find . -name '*.opt'`
	;;
make)
	echo Creating unix distribution directory ...
	$0 cvsconfig > $TEMP_FILE
	make dist > $TEMP_FILE
	archiveName=`grep ".tar.gz" $TEMP_FILE | cut -d " " -f 5`
	echo archiveName = $archiveName
	rm -rf $archiveName
	tar zxf $archiveName.tar.gz
	rm $archiveName.tar.gz

	echo Copying extra files to include directory ...
	cp $archiveName/$MAINLIB/UtSSParser.h $archiveName/$INCDIR
	#cp $archiveName/$GRLIB/dsam.rc $archiveName/$INCDIR

	echo Creating zip archive ...
	newArchiveName=`echo $archiveName | tr -d ".-"`
	rm -rf $newArchiveName
	mv $archiveName $newArchiveName
	zip -r $newArchiveName.zip $newArchiveName > $TEMP_FILE
	rm -rf $newArchiveName
	rm $TEMP_FILE
	
	echo Finished creating $newArchiveName.zip.
	;;
*)
	usage 1 1>&2
esac
