#!/bin/sh
##################
#
# File:		dos-dist
# Purpose:	This script runs all of the commands necessary for configuring AMS
#			for dos compilation
# Author:	L.P.O'Mard
# Created:	26 Sep 2001
# Updated:	
# Copyright:(c) 2001, University of Essex
#
##################

CFGTOOLS=CfgTools
TEMP_FILE=file.tmp

usage()
{
	cat <<EOF
Usage: dos-dist command
commands:
	make      - Create a zip archive distribution.
EOF
	exit $1
}

if [ $# -eq 0 ]; then
	usage 1 1>&2
fi

case  $1 in
make)
	echo Creating unix distribution directory ...
	$CFGTOOLS/cvsconfigure > $TEMP_FILE
	./configure > $TEMP_FILE
	make dist > $TEMP_FILE
	archiveName=`grep ".tar.gz" $TEMP_FILE | cut -d " " -f 5`
	echo archiveName = $archiveName
	rm -rf $archiveName
	tar zxf $archiveName.tar.gz
	rm $archiveName.tar.gz

	echo Creating zip archive ...
	newArchiveName=`echo $archiveName | tr -d ".-"`
	rm -rf $newArchiveName
	mv $archiveName $newArchiveName
	zip -r $newArchiveName.zip $newArchiveName > $TEMP_FILE
	rm -rf $newArchiveName
	rm $TEMP_FILE

	echo Finished creating $newArchiveName.zip.
	;;
*)
	usage 1 1>&2
esac
